import struct
import shutil
import sqlite3
from pathlib import Path
from fastapi.testclient import TestClient
from src.server import app, RIDES_DIR
from src.db import DB_PATH, init_db

client = TestClient(app)

MOCK_GPX = """<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="bikesensor_test" xmlns="http://www.topografix.com/GPX/1/1">
  <trk>
    <trkseg>
      <trkpt lat="54.321" lon="10.123">
        <time>2023-01-01T12:00:00Z</time>
        <ele>10.0</ele>
      </trkpt>
      <trkpt lat="54.322" lon="10.124">
        <time>2023-01-01T12:00:02Z</time>
        <ele>10.0</ele>
      </trkpt>
    </trkseg>
  </trk>
</gpx>
"""

def test_ride_upload():
    # Initialize the database schema for testing
    init_db()
    # 1. Prepare BLE mock packets
    # SYNC 1: 0xA5, idx=0, fs=250, n_axes=6, padding=0
    sync1 = struct.pack("<BIHBB", 0xA5, 0, 250, 6, 0)
    # SYNC 2: 0xA5, idx=250, fs=250, n_axes=6, padding=0
    sync2 = struct.pack("<BIHBB", 0xA5, 250, 250, 6, 0)
    
    # Generate 150 data packets to satisfy 0.5s STFT window (125 samples @ 250Hz)
    ble_packets = [{"timestamp": "2023-01-01T12:00:00.000Z", "hex": sync1.hex()}]
    for i in range(150):
        # DATA: 0x5A, first_idx=i, n_samples=1, 6*int16 BE (zeros except az = 8192)
        data = struct.pack("<BIB", 0x5A, i, 1) + struct.pack(">hhhhhh", 0, 0, 8192, 0, 0, 0)
        t_ms = 4 * i + 4
        ble_packets.append({"timestamp": f"2023-01-01T12:00:00.{t_ms:03d}Z", "hex": data.hex()})
    
    ble_packets.append({"timestamp": "2023-01-01T12:00:01.000Z", "hex": sync2.hex()})

    payload = {
        "gpx_data": MOCK_GPX,
        "ble_data": ble_packets
    }

    # 2. Trigger POST Request to the API
    response = client.post("/api/upload", json=payload)

    # 3. Assert Response
    assert response.status_code == 200
    res_data = response.json()
    assert res_data["status"] == "success"
    
    ride_id = res_data["ride_id"]
    ride_dir = RIDES_DIR / ride_id

    # Verify files were generated by the pipeline
    assert (ride_dir / "raw_gps.gpx").exists()
    assert (ride_dir / "raw_imu.csv").exists()
    assert (ride_dir / "imu.csv").exists()
    assert (ride_dir / "windows.csv").exists()
    assert (ride_dir / "track.csv").exists()

    # 4. Verify SQLite Database Record
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    row = conn.execute("SELECT * FROM rides WHERE id = ?", (res_data["db_id"],)).fetchone()
    conn.close()

    assert row is not None
    assert row["file_path"] == str(ride_dir)
    assert row["distance_m"] > 0

    # 5. Verify GET Endpoint
    list_response = client.get("/api/rides")
    assert list_response.status_code == 200
    list_data = list_response.json()
    assert len(list_data["rides"]) >= 1

    # Clean up files created during the test
    shutil.rmtree(ride_dir)
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("DELETE FROM rides WHERE id = ?", (res_data["db_id"],))
    conn.commit()
    conn.close()

def test_upload_offline():
    # 1. Prepare raw CSV body data
    csv_data = "millis,ax,ay,az\n100,0,0,8192\n200,0,0,8192"
    headers = {
        "X-Ride-Filename": "ride_test_offline.csv",
        "Content-Type": "text/csv"
    }

    # 2. Trigger POST request
    response = client.post("/api/upload-offline", content=csv_data, headers=headers)

    # 3. Assert response
    assert response.status_code == 200
    res_data = response.json()
    assert res_data["status"] == "success"

    # 4. Verify file was saved in the pending directory
    pending_file = Path(__file__).resolve().parent.parent / "data" / "rides" / "pending_vibrations" / "ride_test_offline.csv"
    assert pending_file.exists()
    assert pending_file.read_text() == csv_data

    # 5. Clean up
    pending_file.unlink()
    if pending_file.parent.exists() and not any(pending_file.parent.iterdir()):
        pending_file.parent.rmdir()

def test_upload_offline_unified():
    # 1. Prepare raw CSV body data with unified GPS + Accel logs
    csv_rows = ["millis,ax,ay,az,lat,lon,ele,speed_kmh"]
    for i in range(100):
        millis = i * 10
        if i == 0:
            csv_rows.append(f"{millis},0,0,8192,54.3,10.1,12.0,15.0")
        elif i == 99:
            csv_rows.append(f"{millis},0,0,8192,54.4,10.2,12.0,15.0")
        else:
            csv_rows.append(f"{millis},0,0,8192,,,,")
    csv_data = "\n".join(csv_rows)

    headers = {
        "X-Ride-Filename": "ride_test_unified.csv",
        "Content-Type": "text/csv"
    }

    # 2. Trigger POST request
    response = client.post("/api/upload-offline", content=csv_data, headers=headers)

    # 3. Assert response
    assert response.status_code == 200
    res_data = response.json()
    assert res_data["status"] == "success"
    
    ride_id = res_data["ride_id"]
    ride_dir = RIDES_DIR / ride_id

    # Verify that the server auto-processed it and saved complete outputs
    assert (ride_dir / "raw_imu.csv").exists()
    assert (ride_dir / "imu.csv").exists()
    assert (ride_dir / "windows.csv").exists()
    assert (ride_dir / "track.csv").exists()

    # 4. Verify SQLite Database Record
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    row = conn.execute("SELECT * FROM rides WHERE id = ?", (res_data["db_id"],)).fetchone()
    conn.close()

    assert row is not None
    assert row["file_path"] == str(ride_dir)
    assert row["distance_m"] > 0

    # 5. Clean up
    shutil.rmtree(ride_dir)
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("DELETE FROM rides WHERE id = ?", (res_data["db_id"],))
    conn.commit()
    conn.close()


